### ISSUE TITLE
Alembic Migrations Roadmap

### ISSUE THREAD

**Issue by pmdevita** [pmdevita/hikari-atsume#2]
- [ ] Upgrade
  - [ ] Upgrade only a specific component
  - [ ] Upgrade to a specific checkpoint
  - [ ] Improve command verbosity
- [ ] Downgrade
  - [ ] Downgrade to a specific checkpoint
  - [ ] Improve command verbosity
- [ ] Make Migrations
  - [ ] Detect table/column renames and ask user for input
  - [ ] Improve command verbosity
    - [x] Add/Remove models
    - [x] Add columns
- [ ] Testing?

Some things will just need to be determined through usage:
- Atsume Alembic currently does migrations by simulating all previous migrations on an in memory database and then doing the diff with that, whereas vanilla Alembic expects to be running against your already in use database. Does this cause issues or result in poor performance after a lot of migrations?
